version: '3.1'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    ports:
      - 8070:80
    links:
      - php
    volumes:
      - ./:/var/www/laravel-docker

  php:
    tty: true
    build:
      context: .
      dockerfile: docker/php.dockerfile
    volumes:
      - ./:/var/www/laravel-docker
      - ./.env.docker:/var/www/laravel-docker/.env
    links:
      - postgres
#    entrypoint:
#      - /var/www/laravel-docker/docker/run.sh

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: test-prj
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5433:5432
    volumes:
      - .:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
